kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodeapp
  namespace: default
  lables:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: "rajakonde/nodejs-app:tagversion"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: default
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
        
